MobilesShop.Web/Controllers/BrandsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MobilesShop.Data;
using MobilesShop.Data.Models;
using MobilesShop.Web.Models.Brands;
using System.Linq;

namespace MobilesShop.Web.Controllers
{
    public class BrandsController : Controller
    {
        private readonly MobilesShopDbContext data;

        public BrandsController(MobilesShopDbContext data)
        {
            this.data = data;
        }

        [Authorize]
        public IActionResult Add() => View();

        [Authorize]
        [HttpPost]
        public IActionResult Add(BrandAddFormModel brand)
        {
            if (this.data.Brands.Any(b => b.Name == brand.Name))
            {
                this.ModelState.AddModelError(nameof(brand.Name), "Brand already exists!");
            }
            
            if (!this.ModelState.IsValid)
            {
                return View(brand);
            }

            var brandData = new Brand { Name = brand.Name };

            this.data.Brands.Add(brandData);
            this.data.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

MobilesShop.Web/Controllers/CameraTypesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MobilesShop.Data;
using MobilesShop.Data.Models;
using MobilesShop.Web.Models.CameraTypes;
using System.Linq;

namespace MobilesShop.Web.Controllers
{
    public class CameraTypesController : Controller
    {
        private readonly MobilesShopDbContext data;

        public CameraTypesController(MobilesShopDbContext data)
        {
            this.data = data;
        }

        [Authorize]
        public IActionResult Add() => View();

        [Authorize]
        [HttpPost]
        public IActionResult Add(CameraTypeAddFormModel cameraType)
        {
            if (this.data.CameraTypes.Any(c => c.Name == cameraType.Name))
            {
                this.ModelState.AddModelError(nameof(cameraType.Name), "This Camera Type already exists!");
            }

            if (!this.ModelState.IsValid)
            {
                return View(cameraType);
            }

            var cameraTypeData = new CameraType { Name = cameraType.Name };

            this.data.CameraTypes.Add(cameraTypeData);
            this.data.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

MobilesShop.Web/Controllers/ChipsetsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MobilesShop.Data;
using MobilesShop.Data.Models;
using MobilesShop.Web.Models.Chipsets;
using System.Linq;

namespace MobilesShop.Web.Controllers
{
    public class ChipsetsController : Controller
    {
        private readonly MobilesShopDbContext data;

        public ChipsetsController(MobilesShopDbContext data)
        {
            this.data = data;
        }

        [Authorize]
        public IActionResult Add() => View();

        [Authorize]
        [HttpPost]
        public IActionResult Add(ChipsetAddFormModel chipset)
        {
            if (this.data.Chipsets.Any(c => 
                c.Name == chipset.Name 
                && c.Cores == chipset.Cores
                && c.Clock == chipset.Clock))
            {
                this.ModelState.AddModelError(nameof(chipset.Name), "Chipset already exists!");
            }
            
            if (!this.ModelState.IsValid)
            {
                return View(chipset);
            }

            var chipsetData = new Chipset 
            {
                Name = chipset.Name,
                Cores = chipset.Cores,
                Clock = chipset.Clock
            };

            this.data.Chipsets.Add(chipsetData);
            this.data.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

MobilesShop.Web/Controllers/MobilePhonesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MobilesShop.Data;
using MobilesShop.Data.Models;
using MobilesShop.Web.Models.MobilePhones;
using System.Collections.Generic;
using System.Linq;

namespace MobilesShop.Web.Controllers
{
    public class MobilePhonesController : Controller
    {
        private readonly MobilesShopDbContext data;

        public MobilePhonesController(MobilesShopDbContext data)
            => this.data = data;

        [Authorize]
        public IActionResult Add() => View(new MobilePhoneAddFormModel
        {
            Brands = this.GetMobilePhonesBrands(),
            CameraTypes = this.GetCameraType(),
            Chipsets = this.GetChipset(),
            Displays = this.GetDisplay(),
        });

        [Authorize]
        [HttpPost]
        public IActionResult Add(MobilePhoneAddFormModel mobilePhone)
        {
            if (!this.data.Brands.Any(b => b.Id == mobilePhone.BrandId))
            {
                this.ModelState.AddModelError(nameof(mobilePhone.BrandId), "Brand does not exist!");
            }

            if (!this.data.CameraTypes.Any(c => c.Id == mobilePhone.CameraTypeId))
            {
                this.ModelState.AddModelError(nameof(mobilePhone.CameraTypeId), "Camera Type does not exist!");
            }

            if (!this.data.Chipsets.Any(c => c.Id == mobilePhone.ChipsetId))
            {
                this.ModelState.AddModelError(nameof(mobilePhone.ChipsetId), "Chipset does not exist!");
            }

            if (!ModelState.IsValid)
            {
                mobilePhone.Brands = this.GetMobilePhonesBrands();
                mobilePhone.CameraTypes = this.GetCameraType();
                mobilePhone.Chipsets = this.GetChipset();
                mobilePhone.Displays = this.GetDisplay();

                return View(mobilePhone);
            }

            var mobilePhoneData = new MobilePhone
            {
                BrandId = mobilePhone.BrandId,
                Model = mobilePhone.Model,
                Year = mobilePhone.Year,
                ChipsetId = mobilePhone.ChipsetId,
                DisplayId = mobilePhone.DisplayId,
                Memory = mobilePhone.Memory,
                Storage = mobilePhone.Storage,
                CameraTypeId = mobilePhone.CameraTypeId,
                Battery = mobilePhone.Battery,
                Connectivity = mobilePhone.Connectivity,
                IsDualSim = mobilePhone.IsDualSim,
                Weight = mobilePhone.Weight,
                ImageUrl = mobilePhone.ImageUrl,
                Details = mobilePhone.Details,
                Price = mobilePhone.Price
            };

            this.data.MobilePhones.Add(mobilePhoneData);

            this.data.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        private IEnumerable<BrandDropdownViewModel> GetMobilePhonesBrands()
            => this.data
                .Brands
                .OrderBy(b => b.Name)
                .Select(b => new BrandDropdownViewModel
                {
                    Id = b.Id,
                    Name = b.Name
                })
                .ToList();

        private IEnumerable<CameraTypeDropdownViewModel> GetCameraType()
            => this.data
                .CameraTypes
                .OrderBy(c => c.Name)
                .Select(c => new CameraTypeDropdownViewModel
                {
                    Id = c.Id,
                    Name = c.Name
                })
                .ToList();

        private IEnumerable<ChipsetDropdownViewModel> GetChipset()
            => this.data
                .Chipsets
                .OrderBy(c => c.Name)
                .Select(c => new ChipsetDropdownViewModel
                {
                    Id = c.Id,
                    Name = c.Name
                })
                .ToList();

        private IEnumerable<DisplayDropdownViewModel> GetDisplay()
            => this.data
                .Displays
                .OrderBy(d => d.Name)
                .Select(d => new DisplayDropdownViewModel
                {
                    Id = d.Id,
                    Name = d.Name
                })
                .ToList();
    }
}

MobilesShop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mobile Phones Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mobile Phones Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MobilePhones" asp-action="Add">Add New Mobile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brands" asp-action="Add">Add Brand</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CameraTypes" asp-action="Add">Add Camera Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chipsets" asp-action="Add">Add Chipset</a>
                        </li>
                        </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Mobile Phones Shop
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>